name: Build
on: [push, pull_request]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install package dependencies
      id: cmake_and_ninja
      run: |
        sudo apt-get install ninja-build
        cmake --version
    - name: Configure
      env:
        CC: "gcc-9"
        CXX: "g++-9"
      run: |
        export BOOST_ROOT=$BOOST_ROOT_1_72_0
        cmake -S . \
            -B build \
            -D CMAKE_BUILD_TYPE=$BUILD_TYPE \
            -G Ninja \
            -D CMAKE_MAKE_PROGRAM=ninja
    - name: Build
      run: |
        cmake --build build
    - name: Test
      working-directory: build
      run: |
        ctest .
